[package]
name = "chess5dtools"
version = "0.1.0"
authors = ["Adrien Burgun <adrien.burgun@orange.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "chess5dlib"
path = "lib/main.rs"

[dependencies]
json = "0.12.4"
lazy_static = "1.4.0"
